<a href="https://colab.research.google.com/github/Vedika-Hore/special_assign/blob/main/Optional_task_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from google.colab import files
uploaded=files.upload()
for fn in uploaded.keys():
  print(fn)

Saving car_price_dataset.csv to car_price_dataset.csv
car_price_dataset.csv

In [ ]:
filepath=("/content/car_price_dataset.csv")
df=pd.read_csv(filepath)
print(df)

           Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
0            Kia       Rio  2020          4.2    Diesel          Manual
1      Chevrolet    Malibu  2012          2.0    Hybrid       Automatic
2       Mercedes       GLA  2020          4.2    Diesel       Automatic
3           Audi        Q5  2023          2.0  Electric          Manual
4     Volkswagen      Golf  2003          2.6    Hybrid  Semi-Automatic
...          ...       ...   ...          ...       ...             ...
9995         Kia    Optima  2004          3.7    Diesel  Semi-Automatic
9996   Chevrolet    Impala  2002          1.4  Electric       Automatic
9997         BMW  3 Series  2010          3.0    Petrol       Automatic
9998        Ford  Explorer  2002          1.4    Hybrid       Automatic
9999  Volkswagen    Tiguan  2001          2.1    Diesel          Manual

      Mileage  Doors  Owner_Count  Price
0      289944      3            5   8501
1        5356      2            3  12092
2      231440      4            2  11171
3      160971      2            1  11780
4      286618      3            3   2867
...       ...    ...          ...    ...
9995     5794      2            4   8884
9996   168000      2            1   6240
9997    86664      5            1   9866
9998   225772      4            1   4084
9999   157882      3            3   3342

[10000 rows x 10 columns]

In [ ]:
print("Independent Feature:")
X=df.drop("Price",axis=1)
X

Independent Feature:

,Brand,Model,Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count
0,Kia,Rio,2020,4.2,Diesel,Manual,289944,3,5
1,Chevrolet,Malibu,2012,2.0,Hybrid,Automatic,5356,2,3
2,Mercedes,GLA,2020,4.2,Diesel,Automatic,231440,4,2
3,Audi,Q5,2023,2.0,Electric,Manual,160971,2,1
4,Volkswagen,Golf,2003,2.6,Hybrid,Semi-Automatic,286618,3,3
...,...,...,...,...,...,...,...,...,...
9995,Kia,Optima,2004,3.7,Diesel,Semi-Automatic,5794,2,4
9996,Chevrolet,Impala,2002,1.4,Electric,Automatic,168000,2,1
9997,BMW,3 Series,2010,3.0,Petrol,Automatic,86664,5,1
9998,Ford,Explorer,2002,1.4,Hybrid,Automatic,225772,4,1
9999,Volkswagen,Tiguan,2001,2.1,Diesel,Manual,157882,3,3

In [ ]:
print("Dependent Feature:")
Y=df["Price"]
Y

Dependent Feature:

0        8501
1       12092
2       11171
3       11780
4        2867
        ...
9995     8884
9996     6240
9997     9866
9998     4084
9999     3342
Name: Price, Length: 10000, dtype: int64

In [ ]:
print("Shape of X=",X.shape)

Shape of X= (10000, 9)

In [ ]:
print("Shape of Y=",Y.shape)

Shape of Y= (10000,)

In [ ]:
X=df.select_dtypes(include=["int64"])
encoded_df=pd.get_dummies(data=df,dtype=int)
encoded_df.astype(int)
encoded_df.head()

,Year,Engine_Size,Mileage,Doors,Owner_Count,Price,Brand_Audi,Brand_BMW,Brand_Chevrolet,Brand_Ford,...,Model_Tiguan,Model_Tucson,Model_X5,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_Hybrid,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual,Transmission_Semi-Automatic
0,2020,4.2,289944,3,5,8501,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1,2012,2.0,5356,2,3,12092,0,0,1,0,...,0,0,0,0,0,1,0,1,0,0
2,2020,4.2,231440,4,2,11171,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
3,2023,2.0,160971,2,1,11780,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0
4,2003,2.6,286618,3,3,2867,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1

In [ ]:
from sklearn.preprocessing import StandardScaler
num_cols=["Year","Engine_Size","Mileage","Doors","Price"]
scaler=StandardScaler()
encoded_df[num_cols]=scaler.fit_transform(encoded_df[num_cols])
encoded_df[num_cols]

          Year  Engine_Size   Mileage     Doors     Price
0     1.226021     1.043657  1.630075 -0.447821 -0.113083
1     0.066156    -0.870607 -1.666895 -1.348689  1.040674
2     1.226021     1.043657  0.952303  0.453046  0.744764
3     1.660970    -0.870607  0.135915 -1.348689  0.940431
4    -1.238692    -0.348535  1.591543 -0.447821 -1.923238
...        ...          ...       ...       ...       ...
9995 -1.093709     0.608597 -1.661821 -1.348689  0.009971
9996 -1.383676    -1.392679  0.217346 -1.348689 -0.839523
9997 -0.223810    -0.000487 -0.724937  1.353914  0.325479
9998 -1.383676    -1.392679  0.886638  0.453046 -1.532226
9999 -1.528659    -0.783595  0.100128 -0.447821 -1.770624

[10000 rows x 5 columns]

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(encoded_df,Y,test_size=0.33,random_state=42)

In [ ]:
X_train.shape

(3300,)

In [ ]:
X_test.shape

(3300, 53)

In [ ]:
Y_train.shape

(6700,)

In [46]:
Y_test.shape

(3300,)

In [47]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train,Y_train)

LinearRegression()

In [50]:
print("intercept=",model.intercept_)
print("Coefficient=",model.coef_)

intercept= 8852.964400000003
Coefficient= [-3.03305586e-12  1.36424205e-12  1.12621024e-12 -2.08544293e-12
 -6.96331881e-13  3.11244118e+03  3.63442609e-12  3.51008111e-12
  1.69109171e-12  9.16600129e-13  1.45106149e-12  1.06581410e-12
  1.19459997e-12  2.17714735e-12  1.56674673e-12  1.41042733e-12
 -8.12683254e-13  1.72306613e-13 -2.37321274e-12 -2.77955436e-12
  3.31290551e-13  4.79616347e-14  5.06483744e-13  1.71085368e-12
  1.16706644e-12 -4.01456646e-13  7.43849426e-13  4.35207426e-13
  1.79412041e-13  5.01820807e-13  5.85753668e-13  8.38440428e-13
  1.67865721e-12  1.12798659e-12 -8.35109759e-13 -5.94191363e-13
  4.21440660e-13  7.21200877e-13 -1.79500859e-12  4.05453449e-13
  1.06414877e-13 -1.20570220e-13  4.92050845e-13  1.97619698e-13
  3.27737837e-13 -5.57109914e-13 -3.98570066e-12 -3.82360810e-12
 -3.09083314e-12 -3.78858056e-12  7.78932474e-13  4.07673895e-13
  7.70494779e-13]

In [51]:
Y_pred = model.predict(X_test)
print("Predicted value:",Y_pred[0:11])
print("Actual value:",Y_test.tolist()[0:11])

Predicted value: [ 2000. 11164. 14630.  7334. 10127.  7195.  8292.  6229.  5776.  4979.
 12507.]
Actual value: [2000, 11164, 14630, 7334, 10127, 7195, 8292, 6229, 5776, 4979, 12507]

In [52]:
from sklearn.metrics import r2_score
r2=r2_score(Y_test,Y_pred)
print("R Square=",r2)

R Square= 1.0

In [55]:
import joblib
joblib.dump(model,"model.pkl")
joblib.dump(scaler,"scaler.pkl")
joblib.dump(X_train.columns.to_list(),"column.pkl")

['column.pkl']