<a href="https://colab.research.google.com/github/Vedika-Hore/special_assign/blob/main/Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from google.colab import files
uploaded=files.upload()
for fn in uploaded.keys():
  print(fn)

Saving Combined12.csv to Combined12.csv
Combined12.csv

In [ ]:
filepath='/content/Combined12.csv'
df=pd.read_csv(filepath)
print(df)

        Pressure  global_radiation  temp_mean(c)  temp_min(c)  temp_max(c)  \
0          971.5              0.25           9.0          7.0         10.7
1          972.3              0.97          10.5          6.7         13.5
2          972.4              0.74           6.5          3.9          9.1
3          973.2              0.15           5.1          3.7          7.7
4          975.7              0.12           5.2          2.6          8.3
...          ...               ...           ...          ...          ...
533307    1015.0              2.11          19.7         15.0         27.3
533308    1015.0              2.11          19.7         15.0         27.3
533309    1015.0              2.11          19.7         15.0         27.3
533310    1015.0              2.11          19.7         15.0         27.3
533311    1015.0              2.11          19.7         15.0         27.3

        Wind_Speed  Wind_Bearing  normalized_label
0             0.00             0                 0
1             0.00             0                 0
2             0.00             0                 0
3             0.00             0                 0
4             0.00             0                 0
...            ...           ...               ...
533307        3.14           325                 0
533308       24.07           147                 2
533309        3.30           247                 0
533310       25.41           308                 2
533311        3.22           190                 0

[533312 rows x 8 columns]

In [ ]:
df.head(5)

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
0,971.5,0.25,9.0,7.0,10.7,0.0,0,0
1,972.3,0.97,10.5,6.7,13.5,0.0,0,0
2,972.4,0.74,6.5,3.9,9.1,0.0,0,0
3,973.2,0.15,5.1,3.7,7.7,0.0,0,0
4,975.7,0.12,5.2,2.6,8.3,0.0,0,0

In [ ]:
df.tail(5)

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
533307,1015.0,2.11,19.7,15.0,27.3,3.14,325,0
533308,1015.0,2.11,19.7,15.0,27.3,24.07,147,2
533309,1015.0,2.11,19.7,15.0,27.3,3.30,247,0
533310,1015.0,2.11,19.7,15.0,27.3,25.41,308,2
533311,1015.0,2.11,19.7,15.0,27.3,3.22,190,0

In [ ]:
df.shape

(533312, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 533312 entries, 0 to 533311
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Pressure          533312 non-null  float64
 1   global_radiation  533312 non-null  float64
 2   temp_mean(c)      533312 non-null  float64
 3   temp_min(c)       533312 non-null  float64
 4   temp_max(c)       533312 non-null  float64
 5   Wind_Speed        533312 non-null  float64
 6   Wind_Bearing      533312 non-null  int64
 7   normalized_label  533312 non-null  int64
dtypes: float64(6), int64(2)
memory usage: 32.6 MB

In [ ]:
df.columns

Index(['Pressure', 'global_radiation', 'temp_mean(c)', 'temp_min(c)',
       'temp_max(c)', 'Wind_Speed', 'Wind_Bearing', 'normalized_label'],
      dtype='object')

In [ ]:
df.describe()

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
count,533312.000000,533312.000000,533312.000000,533312.000000,533312.000000,533312.000000,533312.000000,533312.000000
mean,1011.436192,1.310346,12.646057,8.648474,16.871960,11.885974,192.501742,0.906152
std,3.241187,0.897191,6.519240,5.867740,7.692881,7.677086,101.984936,0.992549
min,971.500000,0.030000,-11.100000,-16.000000,-8.500000,0.000000,0.000000,0.000000
25%,1009.800000,0.510000,7.800000,4.500000,11.100000,6.410000,130.000000,0.000000
50%,1012.300000,1.160000,13.200000,9.400000,17.200000,11.040000,190.000000,1.000000
75%,1013.900000,2.010000,17.500000,13.300000,22.400000,15.620000,288.000000,2.000000
max,1015.000000,3.600000,28.600000,22.000000,37.000000,47.530000,359.000000,3.000000

In [ ]:
df.dtypes

Pressure            float64
global_radiation    float64
temp_mean(c)        float64
temp_min(c)         float64
temp_max(c)         float64
Wind_Speed          float64
Wind_Bearing          int64
normalized_label      int64
dtype: object

In [ ]:
df.isnull().sum()

Pressure            0
global_radiation    0
temp_mean(c)        0
temp_min(c)         0
temp_max(c)         0
Wind_Speed          0
Wind_Bearing        0
normalized_label    0
dtype: int64

In [ ]:
df.nunique()

Pressure             332
global_radiation     353
temp_mean(c)         340
temp_min(c)          312
temp_max(c)          393
Wind_Speed          1387
Wind_Bearing         357
normalized_label       4
dtype: int64

In [ ]:
df.sample(5)

,Pressure,global_radiation,temp_mean(c),temp_min(c),temp_max(c),Wind_Speed,Wind_Bearing,normalized_label
297623,1012.7,1.36,6.4,4.2,9.1,17.44,309,3
447486,1014.4,1.29,4.5,0.7,8.8,16.99,150,3
209108,1011.4,2.42,17.3,13.3,21.3,0.00,0,1
482726,1014.7,1.53,12.1,5.3,19.0,5.18,90,1
62154,1007.6,0.99,12.2,11.0,17.1,4.83,340,1

In [ ]:
df.value_counts()

Pressure  global_radiation  temp_mean(c)  temp_min(c)  temp_max(c)  Wind_Speed  Wind_Bearing  normalized_label
1013.5    1.47              17.0          14.8         20.8         0.00        0             0                   6
          2.33              22.0          15.0         29.6         0.00        0             1                   6
          0.70              10.4          7.5          13.7         0.00        0             0                   6
          0.80              9.9           4.5          12.5         0.00        0             1                   6
          1.51              18.8          15.9         23.9         0.00        0             0                   6
                                                                                                                 ..
1010.8    1.87              17.4          13.4         21.8         9.66        150           0                   1
                                                                                20            0                   1
                                                                    9.05        78            0                   1
                                                                    8.65        57            0                   1
                                                                    12.88       170           0                   1
Name: count, Length: 517048, dtype: int64